"""Updated filings schema

Revision ID: 4ec0b4936f22
Revises: 7bcf72f5f70f
Create Date: 2026-08-18 22:39:58.857974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec0b4936f22'
down_revision: Union[str, Sequence[str], None] = '7bcf72f5f70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('filing_type', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_filings_file_type'), table_name='filings')
    op.create_index(op.f('ix_filings_filing_type'), 'filings', ['filing_type'], unique=False)
    op.drop_column('filings', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_filings_filing_type'), table_name='filings')
    op.create_index(op.f('ix_filings_file_type'), 'filings', ['file_type'], unique=False)
    op.drop_column('filings', 'filing_type')
    # ### end Alembic commands ###
