"""add companies and filings

Revision ID: 7bcf72f5f70f
Revises: aaa39145a3ec
Create Date: 2026-08-16 19:47:07.189418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcf72f5f70f'
down_revision: Union[str, Sequence[str], None] = 'aaa39145a3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', name='uq_filings_accession_number')
    )
    op.create_index(op.f('ix_filings_company_id'), 'filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_filings_file_type'), 'filings', ['file_type'], unique=False)
    op.create_index(op.f('ix_filings_filed_at'), 'filings', ['filed_at'], unique=False)
    op.create_index(op.f('ix_filings_reporting_period'), 'filings', ['reporting_period'], unique=False)
    op.create_index(op.f('ix_filings_status'), 'filings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filings_status'), table_name='filings')
    op.drop_index(op.f('ix_filings_reporting_period'), table_name='filings')
    op.drop_index(op.f('ix_filings_filed_at'), table_name='filings')
    op.drop_index(op.f('ix_filings_file_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_company_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
