"""add filing storage key

Revision ID: 91d5b2752897
Revises: 4ec0b4936f22
Create Date: 2026-08-23 09:50:38.838905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d5b2752897'
down_revision: Union[str, Sequence[str], None] = '4ec0b4936f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('storage_key', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'storage_key')
    # ### end Alembic commands ###
