"""add filing chunks

Revision ID: ada29ad7a5f9
Revises: 91d5b2752897
Create Date: 2026-08-23 10:35:41.515406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada29ad7a5f9'
down_revision: Union[str, Sequence[str], None] = '91d5b2752897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'section_key', 'chunk_index', name='uq_chunks_filing_section_index')
    )
    op.create_index(op.f('ix_chunks_filing_id'), 'chunks', ['filing_id'], unique=False)
    op.create_index(op.f('ix_chunks_section_key'), 'chunks', ['section_key'], unique=False)
    op.alter_column('filings', 'reporting_period',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filings', 'reporting_period',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_chunks_section_key'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_filing_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
